<?php
return [
    'router' => [
        'routes' => [
            'tcc.rest.address-type' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/address_type[/:address_type_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\AddressType\\Controller',
                    ],
                ],
            ],
            'tcc.rest.country' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/country[/:country_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Country\\Controller',
                    ],
                ],
            ],
            'tcc.rest.person' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/person[/:person_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Person\\Controller',
                    ],
                ],
            ],
            'tcc.rest.organization' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/organization[/:organization_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Organization\\Controller',
                    ],
                ],
            ],
            'tcc.rest.state' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/state[/:state_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\State\\Controller',
                    ],
                ],
            ],
            'tcc.rest.region' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/region[/:region_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Region\\Controller',
                    ],
                ],
            ],
            'tcc.rest.address' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/address[/:address_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Address\\Controller',
                    ],
                ],
            ],
            'tcc.rest.card' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/card[/:card_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Card\\Controller',
                    ],
                ],
            ],
            'tcc.rest.event-type' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/event_type[/:event_type_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\EventType\\Controller',
                    ],
                ],
            ],
            'tcc.rest.type-user' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/type_user[/:type_user_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\TypeUser\\Controller',
                    ],
                ],
            ],
            'tcc.rest.city' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/city[/:city_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\City\\Controller',
                    ],
                ],
            ],
            'tcc.rest.event' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/event[/:event_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Event\\Controller',
                    ],
                ],
            ],
            'tcc.rest.type-permission' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/type_permission[/:type_permission_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\TypePermission\\Controller',
                    ],
                ],
            ],
            'tcc.rest.ticket' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ticket[/:ticket_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Ticket\\Controller',
                    ],
                ],
            ],
            'tcc.rest.user' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/user[/:user_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\User\\Controller',
                    ],
                ],
            ],
            'tcc.rest.lot' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/lot[/:lot_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Lot\\Controller',
                    ],
                ],
            ],
            'tcc.rest.checkin' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/checkin[/:checkin_id]',
                    'defaults' => [
                        'controller' => 'tcc\\V1\\Rest\\Checkin\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'tcc.rest.address-type',
            1 => 'tcc.rest.country',
            2 => 'tcc.rest.person',
            3 => 'tcc.rest.organization',
            4 => 'tcc.rest.state',
            5 => 'tcc.rest.region',
            6 => 'tcc.rest.address',
            7 => 'tcc.rest.card',
            8 => 'tcc.rest.event-type',
            9 => 'tcc.rest.type-user',
            10 => 'tcc.rest.city',
            11 => 'tcc.rest.event',
            12 => 'tcc.rest.type-permission',
            13 => 'tcc.rest.ticket',
            14 => 'tcc.rest.user',
            15 => 'tcc.rest.lot',
            16 => 'tcc.rest.checkin',
        ],
    ],
    'zf-rest' => [
        'tcc\\V1\\Rest\\AddressType\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\AddressType\\AddressTypeResource',
            'route_name' => 'tcc.rest.address-type',
            'route_identifier_name' => 'address_type_id',
            'collection_name' => 'address_type',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\AddressType\AddressTypeEntity::class,
            'collection_class' => \tcc\V1\Rest\AddressType\AddressTypeCollection::class,
            'service_name' => 'address_type',
        ],
        'tcc\\V1\\Rest\\Country\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Country\\CountryResource',
            'route_name' => 'tcc.rest.country',
            'route_identifier_name' => 'country_id',
            'collection_name' => 'country',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Country\CountryEntity::class,
            'collection_class' => \tcc\V1\Rest\Country\CountryCollection::class,
            'service_name' => 'country',
        ],
        'tcc\\V1\\Rest\\Person\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Person\\PersonResource',
            'route_name' => 'tcc.rest.person',
            'route_identifier_name' => 'person_id',
            'collection_name' => 'person',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Person\PersonEntity::class,
            'collection_class' => \tcc\V1\Rest\Person\PersonCollection::class,
            'service_name' => 'person',
        ],
        'tcc\\V1\\Rest\\Organization\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Organization\\OrganizationResource',
            'route_name' => 'tcc.rest.organization',
            'route_identifier_name' => 'organization_id',
            'collection_name' => 'organization',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Organization\OrganizationEntity::class,
            'collection_class' => \tcc\V1\Rest\Organization\OrganizationCollection::class,
            'service_name' => 'organization',
        ],
        'tcc\\V1\\Rest\\State\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\State\\StateResource',
            'route_name' => 'tcc.rest.state',
            'route_identifier_name' => 'state_id',
            'collection_name' => 'state',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\State\StateEntity::class,
            'collection_class' => \tcc\V1\Rest\State\StateCollection::class,
            'service_name' => 'state',
        ],
        'tcc\\V1\\Rest\\Region\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Region\\RegionResource',
            'route_name' => 'tcc.rest.region',
            'route_identifier_name' => 'region_id',
            'collection_name' => 'region',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Region\RegionEntity::class,
            'collection_class' => \tcc\V1\Rest\Region\RegionCollection::class,
            'service_name' => 'region',
        ],
        'tcc\\V1\\Rest\\Address\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Address\\AddressResource',
            'route_name' => 'tcc.rest.address',
            'route_identifier_name' => 'address_id',
            'collection_name' => 'address',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Address\AddressEntity::class,
            'collection_class' => \tcc\V1\Rest\Address\AddressCollection::class,
            'service_name' => 'address',
        ],
        'tcc\\V1\\Rest\\Card\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Card\\CardResource',
            'route_name' => 'tcc.rest.card',
            'route_identifier_name' => 'card_id',
            'collection_name' => 'card',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Card\CardEntity::class,
            'collection_class' => \tcc\V1\Rest\Card\CardCollection::class,
            'service_name' => 'card',
        ],
        'tcc\\V1\\Rest\\EventType\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\EventType\\EventTypeResource',
            'route_name' => 'tcc.rest.event-type',
            'route_identifier_name' => 'event_type_id',
            'collection_name' => 'event_type',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\EventType\EventTypeEntity::class,
            'collection_class' => \tcc\V1\Rest\EventType\EventTypeCollection::class,
            'service_name' => 'event_type',
        ],
        'tcc\\V1\\Rest\\TypeUser\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\TypeUser\\TypeUserResource',
            'route_name' => 'tcc.rest.type-user',
            'route_identifier_name' => 'type_user_id',
            'collection_name' => 'type_user',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\TypeUser\TypeUserEntity::class,
            'collection_class' => \tcc\V1\Rest\TypeUser\TypeUserCollection::class,
            'service_name' => 'type_user',
        ],
        'tcc\\V1\\Rest\\City\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\City\\CityResource',
            'route_name' => 'tcc.rest.city',
            'route_identifier_name' => 'city_id',
            'collection_name' => 'city',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\City\CityEntity::class,
            'collection_class' => \tcc\V1\Rest\City\CityCollection::class,
            'service_name' => 'city',
        ],
        'tcc\\V1\\Rest\\Event\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Event\\EventResource',
            'route_name' => 'tcc.rest.event',
            'route_identifier_name' => 'event_id',
            'collection_name' => 'event',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Event\EventEntity::class,
            'collection_class' => \tcc\V1\Rest\Event\EventCollection::class,
            'service_name' => 'event',
        ],
        'tcc\\V1\\Rest\\TypePermission\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\TypePermission\\TypePermissionResource',
            'route_name' => 'tcc.rest.type-permission',
            'route_identifier_name' => 'type_permission_id',
            'collection_name' => 'type_permission',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\TypePermission\TypePermissionEntity::class,
            'collection_class' => \tcc\V1\Rest\TypePermission\TypePermissionCollection::class,
            'service_name' => 'type_permission',
        ],
        'tcc\\V1\\Rest\\Ticket\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Ticket\\TicketResource',
            'route_name' => 'tcc.rest.ticket',
            'route_identifier_name' => 'ticket_id',
            'collection_name' => 'ticket',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Ticket\TicketEntity::class,
            'collection_class' => \tcc\V1\Rest\Ticket\TicketCollection::class,
            'service_name' => 'ticket',
        ],
        'tcc\\V1\\Rest\\User\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\User\\UserResource',
            'route_name' => 'tcc.rest.user',
            'route_identifier_name' => 'user_id',
            'collection_name' => 'user',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\User\UserEntity::class,
            'collection_class' => \tcc\V1\Rest\User\UserCollection::class,
            'service_name' => 'user',
        ],
        'tcc\\V1\\Rest\\Lot\\Controller' => [
            'listener' => 'tcc\\V1\\Rest\\Lot\\LotResource',
            'route_name' => 'tcc.rest.lot',
            'route_identifier_name' => 'lot_id',
            'collection_name' => 'lot',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Lot\LotEntity::class,
            'collection_class' => \tcc\V1\Rest\Lot\LotCollection::class,
            'service_name' => 'lot',
        ],
        'tcc\\V1\\Rest\\Checkin\\Controller' => [
            'listener' => \tcc\V1\Rest\Checkin\CheckinResource::class,
            'route_name' => 'tcc.rest.checkin',
            'route_identifier_name' => 'checkin_id',
            'collection_name' => 'checkin',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'idEvent',
                1 => 'numberCard',
                2 => 'type',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \tcc\V1\Rest\Checkin\CheckinEntity::class,
            'collection_class' => \tcc\V1\Rest\Checkin\CheckinCollection::class,
            'service_name' => 'Checkin',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'tcc\\V1\\Rest\\AddressType\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Country\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Person\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Organization\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\State\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Region\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Address\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Card\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\EventType\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\TypeUser\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\City\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Event\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\TypePermission\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Ticket\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\User\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Lot\\Controller' => 'HalJson',
            'tcc\\V1\\Rest\\Checkin\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'tcc\\V1\\Rest\\AddressType\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Country\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Person\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Organization\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\State\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Region\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Address\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Card\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\EventType\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\TypeUser\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\City\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Event\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\TypePermission\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Ticket\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\User\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Lot\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Checkin\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'tcc\\V1\\Rest\\AddressType\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Country\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Person\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Organization\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\State\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Region\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Address\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Card\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\EventType\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\TypeUser\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\City\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Event\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\TypePermission\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Ticket\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\User\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Lot\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
            'tcc\\V1\\Rest\\Checkin\\Controller' => [
                0 => 'application/vnd.tcc.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \tcc\V1\Rest\AddressType\AddressTypeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.address-type',
                'route_identifier_name' => 'address_type_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\AddressType\AddressTypeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.address-type',
                'route_identifier_name' => 'address_type_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Country\CountryEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.country',
                'route_identifier_name' => 'country_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Country\CountryCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.country',
                'route_identifier_name' => 'country_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Person\PersonEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.person',
                'route_identifier_name' => 'person_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Person\PersonCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.person',
                'route_identifier_name' => 'person_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Organization\OrganizationEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.organization',
                'route_identifier_name' => 'organization_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Organization\OrganizationCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.organization',
                'route_identifier_name' => 'organization_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\State\StateEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.state',
                'route_identifier_name' => 'state_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\State\StateCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.state',
                'route_identifier_name' => 'state_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Region\RegionEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.region',
                'route_identifier_name' => 'region_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Region\RegionCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.region',
                'route_identifier_name' => 'region_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Address\AddressEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.address',
                'route_identifier_name' => 'address_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Address\AddressCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.address',
                'route_identifier_name' => 'address_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Card\CardEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.card',
                'route_identifier_name' => 'card_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Card\CardCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.card',
                'route_identifier_name' => 'card_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\EventType\EventTypeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.event-type',
                'route_identifier_name' => 'event_type_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\EventType\EventTypeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.event-type',
                'route_identifier_name' => 'event_type_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\TypeUser\TypeUserEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.type-user',
                'route_identifier_name' => 'type_user_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\TypeUser\TypeUserCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.type-user',
                'route_identifier_name' => 'type_user_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\City\CityEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.city',
                'route_identifier_name' => 'city_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\City\CityCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.city',
                'route_identifier_name' => 'city_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Event\EventEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.event',
                'route_identifier_name' => 'event_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Event\EventCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.event',
                'route_identifier_name' => 'event_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\TypePermission\TypePermissionEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.type-permission',
                'route_identifier_name' => 'type_permission_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\TypePermission\TypePermissionCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.type-permission',
                'route_identifier_name' => 'type_permission_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Ticket\TicketEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.ticket',
                'route_identifier_name' => 'ticket_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Ticket\TicketCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.ticket',
                'route_identifier_name' => 'ticket_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\User\UserEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.user',
                'route_identifier_name' => 'user_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\User\UserCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.user',
                'route_identifier_name' => 'user_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Lot\LotEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.lot',
                'route_identifier_name' => 'lot_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Lot\LotCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.lot',
                'route_identifier_name' => 'lot_id',
                'is_collection' => true,
            ],
            \tcc\V1\Rest\Checkin\CheckinEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.checkin',
                'route_identifier_name' => 'checkin_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \tcc\V1\Rest\Checkin\CheckinCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'tcc.rest.checkin',
                'route_identifier_name' => 'checkin_id',
                'is_collection' => true,
            ],
        ],
    ],
    'zf-apigility' => [
        'db-connected' => [
            'tcc\\V1\\Rest\\AddressType\\AddressTypeResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'address_type',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\AddressType\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Country\\CountryResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'country',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Country\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Person\\PersonResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'person',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Person\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Organization\\OrganizationResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'organization',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Organization\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\State\\StateResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'state',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\State\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Region\\RegionResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'region',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Region\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Address\\AddressResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'address',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Address\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Card\\CardResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'card',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Card\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\EventType\\EventTypeResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'event_type',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\EventType\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\TypeUser\\TypeUserResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'type_user',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\TypeUser\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\City\\CityResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'city',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\City\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Event\\EventResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'event',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Event\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\TypePermission\\TypePermissionResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'type_permission',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\TypePermission\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Ticket\\TicketResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'ticket',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Ticket\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\User\\UserResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'user',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\User\\Controller',
                'entity_identifier_name' => 'id',
            ],
            'tcc\\V1\\Rest\\Lot\\LotResource' => [
                'adapter_name' => 'mydb',
                'table_name' => 'lot',
                'hydrator_name' => \Zend\Hydrator\ArraySerializable::class,
                'controller_service_name' => 'tcc\\V1\\Rest\\Lot\\Controller',
                'entity_identifier_name' => 'id',
            ],
        ],
    ],
    'service_manager' => [
        'factories' => [
            \tcc\V1\Rest\Checkin\CheckinResource::class => \tcc\V1\Rest\Checkin\CheckinResourceFactory::class,
        ],
    ],
];
